# Generated by Django 4.2.6 on 2023-10-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coustmerdetail',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
